### ISSUE TITLE
[DOCS] Doc link is broken.

### ISSUE THREAD

**Issue by asetsuna** [arraiyopensource/torchgeometry#39]
<img width="791" alt="issue" src="https://user-images.githubusercontent.com/2498827/51162969-1d48ff00-18d3-11e9-99e5-5c80593891e8.png">

**Comment by edgarriba** [comment]
yep, finding the best way to automate docs generation, test and deployment. Working on that.

**Comment by edgarriba** [comment]
@asetsuna fixed via 5f55bed2572ed76144e09357d511d03123722b85. Interested in contributing ?
