### ISSUE TITLE
[BUG] test_image crashes with PyTorch 1.0.1

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/torchgeometry#69]
Noticed that there's either a bug somewhere in ``test_image.py`` or in last PyTorch release 1.0.1.
The crash happens when updating to ``pytorch-cpu==1.0.1`` in TravisCI.

**UPDATE (11/02/2019):**

Confirmed that after installing ``pytorch-cpu==1.0.1`` through the script ``setup_travis_env.sh`` there is a crash only in TravisCI. Tried to reproduce in local and seems to work as expected. Poltergeist in new stable release v1.0.1?

Link to the PR (https://github.com/arraiyopensource/torchgeometry/pull/72) and build:
https://travis-ci.com/arraiyopensource/torchgeometry/jobs/176774886)

How to reproduce the issue:
```bash
git clone https://github.com/arraiyopensource/torchgeometry
cd torchgeometry
./setup_travis_env.sh
source path.bash.inc
pytest test
```
You should get green lights, TravisCI don't.

Screenshot of the log:
![screenshot from 2019-02-06 12-55-53](https://user-images.githubusercontent.com/5157099/52340372-e8caed80-2a0f-11e9-80fc-a25af2b18ed6.png)

**Comment by soumith** [comment]
is there a way you can get a stack-trace.
You can probably modify your script to make it run under gdb and print a stack-trace to the console.

**Comment by edgarriba** [comment]
@soumith thanks for your time. It turns out that the issue has been solved by itself restarting again the jobs (already tried that before though). I guess they did some update in TravisCI or something since I didn't touch my code and I guess you didn't update the pytorch wheels for v1.0.1 right ?
