### ISSUE TITLE
[BUG] Regarding relative_pose

### ISSUE THREAD

**Issue by versatran01** [arraiyopensource/torchgeometry#75]
Either this math is wrong or I misunderstood some of the notation here.

P_1^{2} = \begin{bmatrix} R_2 R_1^T & R_1^T (t_2 - t_1) \\ \mathbf{0} &
        1\end{bmatrix}

I believe the correct forms should be (assuming when you say pose, it is wrt to some common frame, thus T_1 is actually T_1^W, T_2 is actually T_2^W. Then the relative transformation from 1 to 2 is T_2^1 which is

T_2^1 = T_1 ^ -1 * T_2 = R_1^T * R_2 | R_1^T * (t_2 - t_1)

So the rotation is flipped.

or 

T_1^2 = T_2 ^ -1 * T_1 = R_2^T * R_1 | R_2^T * (t_1 - t_2)

**Comment by edgarriba** [comment]
@versatran01 thanks for reporting. I'll take a look at it today and I'll add as a TODO for next week release.

**Comment by tiancheng-zhi** [comment]
My code broke down due to this bug too... I manually calculate relative pose then my code works.

**Comment by edgarriba** [comment]
@tiancheng-zhi nice to hear about new users of the library. Notice that I'm fixing the issue in https://github.com/arraiyopensource/torchgeometry/pull/79. You are very welcomed to share with us your thoughts.

**Comment by edgarriba** [comment]
closed in favor #79
